# LH_table_file = 'Data/winemag_sample.csv'
# problem_sets_file = 'Data/Benchmark/problem_sets.csv'
dataset_name = 'IMDB'
problem_sets_file = 'Data/Benchmark/{}/problem_sets.csv'.format(dataset_name)
test_size_for_cv = 0.2
foofah_time_limit = 10
number_of_rows_for_foofah = 50
valid_solution_threshold = 0.5
regression_eval_threshold = 1.1
textual_attributes_with_small_domain_threshold = 50
duplicate_column_overlap_threshold = 0.8
noise_rate_for_duplicate_column = 0.08
column_nan_threshold = 0.5
noise_rate_for_nans = 0.8
bootstrap_size = 20
max_size_lhd_fd = 3
new_inf = 10000000000
CATEGORICAL_UPPER_BOUND = 5
